config/routes.rb
Rails.application.routes.draw do
  get  'users/sign_up' => 'users#noautorizate'
  devise_for :users
  
  root 'home#index'

  get 'consulting/school' => 'consulting#school'
  get 'consulting/financial' => 'consulting#financial'
  get 'consulting/company' => 'consulting#company'
  get 'consulting/accounting' => 'consulting#accounting'
  get 'consulting/public' => 'consulting#public'

  get 'contacts/contacts' => 'contacts#contacts'

  get 'forms/doubt' => 'forms#doubt'
  get 'forms/budget' => 'forms#budget'
  get 'forms/work' => 'forms#work'
  get 'forms/:id/completed' => 'forms#completed', as: :completed_form
  get 'forms/confirm' => 'forms#confirm'

  get 'courses' => 'courses#index'
  get 'courses/:id' => 'courses#show', as: :course

  get 'institutional/me' => 'institutional#me'
  get 'institutional/equip' => 'institutional#equip'  

  get 'admin/courses' => 'admin#courses', as: :admin_courses
  get 'admin/courses/:id/edit' => 'admin#edit_course', as: :edit_course
  get 'admin/courses/new' => 'admin#new_course', as: :new_course
  get 'admin/mypictures' => 'admin#mypictures', as: :admin_mypictures
  get 'admin/mypictures/new' => 'admin#new_picture', as: :new_picture
  get 'admin/mypictures/:id/edit' => 'admin#edit_picture', as: :edit_picture
  get 'admin/mypictures/:id' => 'admin#show_picture', as: :picture
  delete  'admin/mypictures/:id' => 'mypictures#destroy'
  get 'admin/doubts/index' => 'admin#doubts_index'
  get 'admin/budgets/index' => 'admin#budgets_index'
  get 'admin/resumes/index' => 'admin#resumes_index'
  get 'admin/doubts_open' => 'admin#doubts_open'
  get 'admin/doubts_closed' => 'admin#doubts_closed'
  get 'admin/budgets_open' => 'admin#budgets_open'
  get 'admin/budgets_closed' => 'admin#budgets_closed'
  get 'admin/resumes_open' => 'admin#resumes_open'
  get 'admin/resumes_closed' => 'admin#resumes_closed'
  get 'admin/forms/:id' => 'admin#show_form', as: :form
  delete 'admin/forms/:id' => 'forms#destroy'

  resources :admin
  resources :courses
  resources :forms, only:[:new, :create]

  resources :mypictures, only:[:index, :create, :update, :show] do
    resources :file_uploads, only:[:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/form.rb
class Form < ApplicationRecord
	has_many_attached :files, dependent: :destroy
end

app/models/mypicture.rb
class Mypicture < ApplicationRecord
	has_many_attached :files, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_user!

	def courses
		@courses = Course.all
	end

	def new_course
		@course = Course.new
	end

	def edit_course
		@course = Course.find(params[:id])
	end

	def mypictures
		@pictures = Mypicture.all
	end

	def new_picture
		@picture = Mypicture.new
	end

	def edit_picture
		@picture = Mypicture.find(params[:id])
	end

	def show_picture
		@picture = Mypicture.find(params[:id])
	end

	def doubts_open
		@forms = Form.where(category: 'doubt', status: 'NOK')
		@title = 'DUVIDAS EM ABERTO'
		render 'form'
	end

	def doubts_closed
		@forms = Form.where(category: 'doubt', status: 'OK')
		@title = 'DUVIDAS RESPONDIDAS'
		render 'form'
	end

	def budgets_open
		@forms = Form.where(category: 'budget', status: 'NOK')
		@title = 'ORÇAMENTOS EM ABERTO'
		render 'form'
	end

	def budgets_closed
		@forms = Form.where(category: 'budget', status: 'OK')
		@title = 'ORÇAMENTOS RESPONDIDOS'
		render 'form'
	end

	def resumes_open
		@forms = Form.where(category: 'resume', status: 'NOK')
		@title = 'NOVOS CURRICULOS'
		render 'form'
	end

	def resumes_closed
		@forms = Form.where(category: 'resume', status: 'OK')
		@title = 'CURRICULOS ARQUIVADOS'
		render 'form'
	end

	def show_form
		@form = Form.find(params[:id])
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	def index
		@courses = Course.all
	end

	def create
		values = params.require(:course).permit!
		@course = Course.create values

		if @course.save
			redirect_to admin_courses_path, notice: 'Curso Cadastrado!'
		end
	end

	def update
		@course = Course.find(params[:id])
		values = params.require(:course).permit!

		@course.update values

		redirect_to admin_courses_path, notice: 'Alteração Salva!'
	end

	def destroy
		id = params[:id]
		Course.destroy id

		redirect_to admin_courses_path, notice: 'Curso Excluído!'
	end

	def show
		@course = Course.find(params[:id])
	end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController

	before_action :new_form, only:[:budget, :doubt, :work]

	def create
		values = params.require(:form).permit!
		@form = Form.create values
		@form.update(category: params[:category], status: 'NOK')

		if params[:files] != nil
			@form.files.attach(params[:form][:files])
		end
		
		redirect_to forms_confirm_path
	end

	def completed
		@form = Form.find(params[:id])
		@form.update(status: 'OK')

		if @form.category == 'doubt'
			redirect_to admin_doubts_open_path, notice: 'Duvida Respondida!'
		elsif @form.category == 'budget'
			redirect_to admin_budgets_open_path, notice: 'Orçamento Respondido!'
		elsif @form.category == 'resume'
			redirect_to admin_resumes_open_path, notice: 'Curriculo Visto!'
		end
	end

	def destroy
		@form = Form.find(params[:id])
		Form.destroy params[:id]

		if @form.category == 'doubt'
			if @form.status == 'OK'
				redirect_to admin_doubts_closed_path, notice: 'Apagado com Sucesso!'
			else
				redirect_to admin_doubts_open_path, notice: 'Apagado com Sucesso!'
			end	
		elsif @form.category == 'budget'
			if @form.status == 'OK'
				redirect_to admin_budgets_closed_path, notice: 'Apagado com Sucesso!'
			else
				redirect_to admin_budgets_open_path, notice: 'Apagado com Sucesso'
			end	
		elsif @form.category == 'resume'
			if @form.status == 'OK'
				redirect_to admin_resumes_closed_path, notice: 'Apagado com Sucesso!'
			else
				redirect_to admin_resumes_open_path, notice: 'Apagado com Sucesso!'
			end	
		end
	end

	def show
		@form = Form.find(params[:id])
	end

	private

	def new_form
		@form = Form.new
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def date_br(date)
		if date != nil
			date = date.strftime("%d/%m/%Y")
		end
	end
end

app/helpers/consulting_helper.rb
module ConsultingHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/file_uploads_helper.rb
module FileUploadsHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/institutional_helper.rb
module InstitutionalHelper
end

app/helpers/mypictures_helper.rb
module MypicturesHelper
end

app/views/admin/_form_course.html.erb
<%= form_for @course do |f| %>
	<div class="form-group">
		<%= f.label :titulo %>
		<%= f.text_field :title, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :descrição %>
		<%= f.text_area :description, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label 'Conteúdo do Curso' %>
		<%= f.text_area :matters, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.submit :salvar, class: 'btn btn-success' %>
	</div>
<% end %>

app/views/admin/_form_picture.html.erb
<%= form_for @picture do |f| %>
	<div class="form-group">
		<%= f.label :nome %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.label :descrição %>
		<%= f.text_area :description, class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= f.submit :salvar, class: 'btn btn-success' %>
	</div>
<% end %>

app/views/admin/_logobar.html.erb
<div class="row">
	<div class="col-lg-8 col-md-8 col-sm-12">
		<p style="margin: 2em auto; margin-right: 4em; text-align: right;"><%= link_to (image_tag 'logo.png', :width=> '300px'), admin_index_path %>
		</p>
	</div>
	<div class="col-lg-4 col-md-4 col-sm-12">
		<p style="text-align: right; margin-top: 4em; margin-right: 3em;"><%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'btn btn-danger', data:{confirm: 'Deseja encerrar a sessão?'} %></p>
	</div>
</div>

<% if flash[:notice] %>
	<div class="row">
		<div class="container">
			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="alert alert-info">
					<%= flash[:notice] %>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/admin/budgets_index.html.erb
<%= render 'logobar' %>

<div class="row">
	<div class="container">
		<div class="col-lg-2"></div>
		<%= link_to admin_budgets_open_path do %>
			<div class="col-lg-3 col-md-4 col-sm-12 box-admin">
				<p>Orçamentos em Aberto</p>
			</div>
		<% end %>

		<%= link_to admin_budgets_closed_path do %>
			<div class="col-lg-3 col-md-4 col-sm-12 box-admin">
				<p>Orçamentos Respondidos</p>
			</div>
		<% end %>
	</div> 
</div>

app/views/admin/courses.html.erb
<%= render 'logobar' %>

<div class="row">
	<div class="container">
		<div class="col-lg-12 col-md-12 col-sm-12">
			<p style="margin-bottom: 1em; text-align: right;"><%= link_to 'Novo Curso', new_course_path, class: 'btn btn-primary' %></p>
			<table class="table table-bordered">
				<thead>
					<th>Curso</th>
					<th>Data de Criação</th>
				</thead>
				<tbody>
					<% @courses.each do |course| %>
					<tr>
						<td><%= course.title %></td>	
						<td><%= date_br(course.created_at) %></td>
						<td><%= link_to 'exibir', course_path(course), class: 'btn btn-primary' %></td>
						<td><%= link_to 'editar', edit_course_path(course), class: 'btn btn-warning' %></td>
						<td><%= link_to 'excluir', course_path(course), method: :delete, class: 'btn btn-danger', data:{confirm: 'Deseja Excluir Esse Curso?'} %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div> 
</div>

app/views/admin/doubts_index.html.erb
<%= render 'logobar' %>

<div class="row">
	<div class="container">
		<div class="col-lg-2"></div>
		<%= link_to admin_doubts_open_path do %>
			<div class="col-lg-3 col-md-4 col-sm-12 box-admin">
				<p>Duvidas em Aberto</p>
			</div>
		<% end %>

		<%= link_to admin_doubts_closed_path do %>
			<div class="col-lg-3 col-md-4 col-sm-12 box-admin">
				<p>Duvidas Respondidas</p>
			</div>
		<% end %>
	</div> 
</div>

app/views/admin/edit_course.html.erb
<%= render 'logobar' %>

<div class="container">
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12">

			<div class="form-center">
				<h1>EDITAR CURSO</h1>

				<%= render 'form_course' %>
			</div>
		</div>
	</div>
</div>

app/views/admin/edit_picture.html.erb
<%= render 'logobar' %>

<div class="container">
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12">

			<div class="form-center">
				<h1>EDITAR ÁLBUM</h1>

				<%= render 'form_picture' %>
			</div>
		</div>
	</div>
</div>

app/views/admin/index.html.erb
<%= render 'logobar' %>

<div class="row">
	<div class="container">
		<%= link_to admin_courses_path do %>
			<div class="col-lg-3 col-md-4 col-sm-12 box-admin">
				<p>CURSOS</p>
			</div>
		<% end %>
		<%= link_to admin_mypictures_path do %>
			<div class="col-lg-3 col-md-4 col-sm-12 box-admin">
				<p>GALERIA</p>
			</div>
		<% end %>
		<%= link_to root_path do %>
			<div class="col-lg-3 col-md-4 col-sm-12 box-admin">
				<p>CONCURSOS</p>
			</div>
		<% end %>
		<%= link_to admin_budgets_index_path do %>
			<div class="col-lg-3 col-md-4 col-sm-12 box-admin">
				<p>ORÇAMENTOS</p>
			</div>
		<% end %>
		<%= link_to admin_doubts_index_path do %>
			<div class="col-lg-3 col-md-4 col-sm-12 box-admin">
				<p>DUVIDAS</p>
			</div>
		<% end %>
		<%= link_to admin_resumes_index_path do %>
			<div class="col-lg-3 col-md-4 col-sm-12 box-admin">
				<p>CURRÍCULOS</p>
			</div>
		<% end %>
	</div>

</div>

app/views/admin/mypictures.html.erb
<%= render 'logobar' %>

<div class="row">
	<div class="container">
		<div class="col-lg-12 col-md-12 col-sm-12">
			<h2><b>MEUS ALBUNS</b></h2>
			<p style="margin-bottom: 1em; text-align: right;"><%= link_to 'Novo Album', new_picture_path, class: 'btn btn-primary' %></p>
			<table class="table table-bordered">
				<thead>
					<th>Nome do Album</th>
					<th>Data de Criação</th>
				</thead>
				<tbody>
					<% @pictures.each do |picture| %>
					<tr>
						<td><%= picture.name %></td>	
						<td><%= date_br(picture.created_at) %></td>
						<td><%= link_to 'exibir', picture_path(picture), class: 'btn btn-primary' %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div> 
</div>

app/views/admin/new_course.html.erb
<%= render 'logobar' %>

<div class="container">
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12">

			<div class="form-center">
				<h1>NOVO CURSO</h1>

				<%= render 'form_course' %>
			</div>
		</div>
	</div>
</div>

app/views/admin/resumes_index.html.erb
<%= render 'logobar' %>

<div class="row">
	<div class="container">
		<div class="col-lg-2"></div>
		<%= link_to admin_resumes_open_path do %>
			<div class="col-lg-3 col-md-4 col-sm-12 box-admin">
				<p>Currículos Não Vistos</p>
			</div>
		<% end %>

		<%= link_to admin_resumes_closed_path do %>
			<div class="col-lg-3 col-md-4 col-sm-12 box-admin">
				<p>Currículos Arquivados</p>
			</div>
		<% end %>
	</div> 
</div>

app/views/admin/show_form.html.erb
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12">
		<p style="margin: 2em auto; text-align: center;"><%= link_to (image_tag 'logo.png', :width=> '300px'), admin_index_path %>
			<%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'btn btn-destroy' %>
		</p>
	</div>
</div>

<% if flash[:notice] %>
	<div class="row">
		<div class="container">
			<div class="col-lg-12 col-md-12 col-sm-12">
				<div class="alert alert-info">
					<%= flash[:notice] %>
				</div>
			</div>
		</div>
	</div>
<% end %>

<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12">
		<div class="container form-center">
			<div style="margin-bottom: 1em;">
				<span>
					<input type='button' value='Voltar' onclick='history.go(-1)' class="btn btn-default"  />
				</span>
				<% if @form.status == 'NOK' %>
					<span>
						<%= link_to 'Marcar como Respondido', completed_form_path(@form), class: 'btn btn-success' %>
					</span>
				<% end %>
				<span><%= link_to 'Exluir', form_path(@form), method: :delete, class: 'btn btn-danger', data:{confirm: 'Deseja excluir?'}  %></span>
			</div>
			
			<%= form_for @form do |f| %>
				<div class="form-group">
					<%= f.label :nome %>
					<%= f.text_field :name, class: 'form-control', :disabled=>true %>
				</div>
				<div class="form-group">
					<%= f.label :email %>
					<%= f.text_field :email, class: 'form-control', :disabled=>true %>
				</div>
				<div class="form-group">
					<%= f.label :telefone %>
					<%= f.text_field :phone, class: 'form-control', :disabled=>true %>
				</div>
				<% if @form.category != 'resume' %>
					<div class="form-group">
						<%= f.label :empresa %>
						<%= f.text_field :company, class: 'form-control', :disabled=>true %>
					</div>
					<div class="form-group">
						<%= f.label :segmento %>
						<%= f.text_field :segment, class: 'form-control', :disabled=>true %>
					</div>
				<% end %>
				<div class="form-group">
					<%= f.label :descrição %>
					<%= f.text_area :description, class: 'form-control', :disabled=>true %>
				</div>
				<% if @form.category == 'resume' %>
					<div class="form-group">
						<%= f.label :curriculo %>
						<% unless @form.files.empty? %>	
							<p><%= link_to 'curriculo anexo', url_for(@form.files.first) %></p>
						<% else %>
							<p>Não há anexos</p>
						<% end %>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/admin/show_picture.html.erb
<%= render 'logobar' %>

<div class="container">
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12">

			<div class="form-center">
				<h1>Album: <%= @picture.name %></h1>
				<span><%= link_to 'Voltar', admin_mypictures_path, class: 'btn btn-default' %></span>
				<span><%= link_to 'Adicionar Foto', new_mypicture_file_upload_path(@picture), class: 'btn btn-primary' %></span>
				<span><%= link_to 'editar', edit_picture_path(@picture), class: 'btn btn-warning' %></span>
				<span><%= link_to 'excluir álbum', picture_path(@picture), method: :delete, class: 'btn btn-danger', data:{confirm: 'Deseja excluir este álbum?'} %></span>

				<%= form_for @picture do |f| %>
					<div class="form-group">
						<br>
						<%= f.label :nome %>
						<%= f.text_field :name, class: 'form-control', :disabled=>true %>
					</div>
					<div class="form-group">
						<%= f.label :descrição %>
						<%= f.text_area :description, class: 'form-control', :disabled=>true %>
					</div>
					<div class="form-group">
						<%= f.label :fotos %><br>
						<% @picture.files.each do |file| %>
							<div class="col-lg-3 col-md-3 col-sm-12" style="text-align: center; height: 150px; margin-bottom: 3em;">
									<%= link_to (image_tag file, :width=>'100%', :height=>'100%'), url_for(file) %>
									<%= link_to "Remover", mypicture_file_upload_path(@picture, file), method: :delete, data: { confirm: "Tem certeza?" } %>		
							</div>	
						<% end %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Comaserv - Consultoria e Acessoria</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="primary-container">
      <%= yield %>
    </div>

    <div class="row footer-link">
      <div class="col-lg-12 col-md-12 col-sm-12 footer-1">
        <div class="col-lg-2 col-md-2 col-sm-2" align="left">
          <h4>INSTITUCIONAL</h4>
          <p><%= link_to 'Quem Somos?', institutional_me_path %></p>
          <p><%= link_to 'Nossa Equipe', institutional_equip_path %></p>
          <p><%= link_to 'Nossa Galeria', mypictures_path %></p>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2" align="left">
          <h4>CURSOS</h4>
          <p><%= link_to 'Agenda de Cursos', courses_path %></p>
          <p><%= link_to 'Inscrições' %></p>
          <p><%= link_to 'Cursos em Parceria' %></p>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2" align="left">
          <h4>CONSULTORIA</h4>
          <p><%= link_to 'Escolar', consulting_school_path %></p>
          <p><%= link_to 'Financeira', consulting_financial_path %></p>
          <p><%= link_to 'Empresarial', consulting_company_path %></p>
          <p><%= link_to 'Contábil', consulting_accounting_path %></p>
          <p><%= link_to 'Pública', consulting_public_path %></p>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2" align="left">
          <h4>CONCURSOS</h4>
          <p>Abertos</p>
          <p>Em Andamento</p>
          <p>Concluídos</p>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2" align="left">
          <h4>FALE CONOSCO</h4>
          <p><%= link_to 'Duvidas', forms_doubt_path %></p>
          <p><%= link_to 'Orçamentos', forms_budget_path %></p>
          <p><%= link_to 'Nossos Contatos', contacts_contacts_path %></p>
        </div>
           <div class="col-lg-2 col-md-2 col-sm-2" align="left">
          <h4>TRABALHE CONOSCO</h4>
          <p><%= link_to 'Faça Parte', forms_work_path %></p>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12">
         <div class="footer-2">
          <p>&copy; ComaServ Todos os direitos reservados</p>
        </div>
      </div>
    </div>
  </body>
</html>